default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: perfume_back_end_development
  username: postgres
  password: sadaf313

test:
  <<: *default
  database: perfume_back_end_test
  username: postgres
  password: sadaf313

production:
  <<: *default
  database: perfume_back_end_production
  username: perfume_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
